language: python
python:
  - 2.6
  - 2.7
# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends fsl afni
  - sudo apt-get install -qq fsl-atlases
  - source /etc/fsl/fsl.sh

# Install packages
install:
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes numpy scipy nose traits networkx dateutil
  - pip install nibabel --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - pip install https://github.com/RDFLib/rdflib/archive/master.zip
  - pip install https://github.com/satra/prov/archive/enh/rdf.zip
  - python setup.py install

# Run test
script:
  - nosetests --with-doctest --with-cov --cov nipype --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
